name: Update Immortalwrt Packages
on: 
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'

env:
  TZ: Asia/Shanghai

jobs:
  Update_ImmortalWrt_Packages:
    runs-on: ubuntu-latest

    permissions: 
      contents: write
      actions: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  
          ref: main

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U GitPython

      - name: Update Packages
        id: update
        run: |
          python packages.py
          rm -rf __pycache__
          echo "message=$(date +'%Y-%m-%d_%H%M%S')" >> $GITHUB_OUTPUT

      - name: Commit
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          status=$(git status -sb)
          if [ "$status" == "## main...origin/main" ];then
              echo "nothing to commit, working tree clean"
          else
          git add .
          git commit -m "Sync $(TZ='Asia/Shanghai' date +%Y-%m-%d" "%H:%M:%S)"
          fi
        
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: main      

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2.0.0
        with:
          retain_days: 0
          keep_minimum_runs: 2
          token: ${{ secrets.GITHUB_TOKEN }}
